[package]
name = "step-04"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.8.3"
log = "0.4"
tokio = { version = "1.6", features = ["io-util", "macros", "net", "rt-multi-thread"] }
tower-lsp = "0.14.1"
tower-service = "0.3"
serde_json = "1.0"

[build-dependencies]
cc = "1.0"
